language: perl
matrix:
 include:
  - perl: "5.22"
    env: WITH_IPC_RUN=1
  - perl: "5.20"
  - perl: "5.18"
    env: WITH_IPC_RUN=1
  - perl: "5.16"
  - perl: "5.14"
  - perl: "5.12"
  - perl: "5.10"
  - perl: "5.8"
    env: WITH_IPC_RUN=1
  - perl: "5.8"
    env: WITH_IPC_RUN=1 USE_TIME_HIRES_VERSION=1.9716

before_install:
 - '[ "$WITH_IPC_RUN" = 1 ]             && cpanm --quiet --notest IPC::Run                                || true'
 - '[ "$USE_TIME_HIRES_VERSION" != "" ] && cpanm --quiet --notest Time::HiRes~"==$USE_TIME_HIRES_VERSION" || true'

branches:
 except:
  - /appveyor/
sudo: false
